name: Code checks
description: Lint and unit tests

runs:
  using: "composite"
  - name: Configure node
    uses: ./.github/actions/setup-project

  - name: Lint code
    run: npm run lint

  - name: Run unit tests
    run: npm run test